name: CI

on:
  push:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        netVersion: [5.0.*, 6.0.*, 7.0.*]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Get .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.netVersion }}
    - name: Publish
      run: |
        dotnet publish ./src/app/app.csproj /p:OutputType=exe
